name: Send Daily Image

on:
    schedule:
      # 每天 8:00 触发（UTC 时间，对应北京时间 16:00，需调整）
      - cron: '0 0/1 * * *' 
    workflow_dispatch:     # 支持手动触发
jobs:
    send-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12.1'
        
        - name: 安装 Python 依赖
          run: |
            python -m pip install --upgrade pip
            pip install requests  # 核心依赖
            
        - name: Run script
          run: |
            python send_image.py